# Generated by Django 3.2 on 2021-05-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projet',
            name='date_approb',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='date_cloture',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='date_remb',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='date_vigueur',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='id',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='les_annee',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='montant',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='montant_usd',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='part_bailleur',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='part_etat',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='population',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='region',
        ),
        migrations.AlterField(
            model_name='projet',
            name='code',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='projet',
            name='id_projet',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='projet',
            name='updated',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterModelTable(
            name='projet',
            table='projet',
        ),
    ]
