# Generated by Django 3.2 on 2021-05-27 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0002_auto_20210527_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='created',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='projet',
            name='id_projet',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Indicateur',
            fields=[
                ('id_indicateur', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=200, unique=True)),
                ('libelle', models.CharField(blank=True, default='', max_length=500)),
                ('niveau', models.CharField(blank=True, default='', max_length=500)),
                ('unite', models.CharField(blank=True, default='', max_length=500)),
                ('nature', models.CharField(blank=True, default='', max_length=500)),
                ('calcul', models.CharField(blank=True, default='', max_length=500)),
                ('reference', models.CharField(blank=True, default='0', max_length=500)),
                ('cible', models.CharField(blank=True, default='', max_length=200)),
                ('valeur', models.CharField(blank=True, default='', max_length=500)),
                ('date_approb', models.CharField(blank=True, default='', max_length=500)),
                ('created', models.CharField(blank=True, default='', max_length=500)),
                ('updated', models.CharField(blank=True, default='', max_length=500)),
                ('id_projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicateurs', to='indicators.projet')),
            ],
            options={
                'db_table': 'indicateur',
            },
        ),
    ]
