# Generated by Django 3.2 on 2021-06-01 20:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0003_auto_20210527_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annee',
            fields=[
                ('id_annee', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=200, unique=True)),
                ('observation', models.CharField(blank=True, default='', max_length=500)),
                ('resume', models.CharField(blank=True, default='', max_length=500)),
                ('created', models.CharField(blank=True, default='', max_length=500)),
                ('updated', models.CharField(blank=True, default='', max_length=500)),
            ],
            options={
                'db_table': 'annee',
            },
        ),
        migrations.RemoveField(
            model_name='indicateur',
            name='date_approb',
        ),
        migrations.RemoveField(
            model_name='indicateur',
            name='id_projet',
        ),
        migrations.AddField(
            model_name='indicateur',
            name='datemaj',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='indicateur',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='indicateur',
            name='projet',
            field=models.ForeignKey(db_column='id_projet', default='null', on_delete=django.db.models.deletion.CASCADE, related_name='indicateurs', to='indicators.projet'),
        ),
        migrations.AddField(
            model_name='projet',
            name='montant',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='projet',
            name='montant_usd',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='projet',
            name='part_bailleur',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.CreateModel(
            name='Indicateursuivi',
            fields=[
                ('id_indicateursuivi', models.AutoField(primary_key=True, serialize=False)),
                ('valeur', models.CharField(blank=True, default='', max_length=200)),
                ('datemaj', models.DateField(default=django.utils.timezone.now)),
                ('observation', models.TextField(blank=True, default='')),
                ('created', models.CharField(blank=True, default='', max_length=500)),
                ('updated', models.CharField(blank=True, default='', max_length=500)),
                ('indicateur', models.ForeignKey(db_column='id_indicateur', on_delete=django.db.models.deletion.CASCADE, related_name='indicateursSuivi', to='indicators.indicateur')),
            ],
            options={
                'db_table': 'indicateursuivi',
            },
        ),
        migrations.CreateModel(
            name='Indicateurplan',
            fields=[
                ('id_indicateurplan', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(blank=True, default='', max_length=500)),
                ('cible', models.CharField(blank=True, default='', max_length=500)),
                ('valeur', models.CharField(blank=True, default='', max_length=500)),
                ('datemaj', models.CharField(blank=True, default='', max_length=500)),
                ('observation', models.CharField(blank=True, default='', max_length=500)),
                ('resume', models.CharField(blank=True, default='', max_length=500)),
                ('created', models.CharField(blank=True, default='', max_length=500)),
                ('updated', models.CharField(blank=True, default='', max_length=500)),
                ('annee', models.ForeignKey(db_column='id_annee', on_delete=django.db.models.deletion.CASCADE, related_name='indicateurPlan_annee', to='indicators.indicateur')),
                ('indicateur', models.ForeignKey(db_column='id_indicateur', on_delete=django.db.models.deletion.CASCADE, related_name='indicateurPlan', to='indicators.indicateur')),
            ],
            options={
                'db_table': 'indicateurplan',
            },
        ),
    ]
